import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";

// ── helpers ───────────────────────────────────────────────────────────────
function fmtINR(n) {
  // jsPDF / Helvetica cannot render the Rs symbol properly on all systems
  // Use plain "Rs." which is safe ASCII
  return `Rs. ${Number(n || 0).toLocaleString("en-IN")}`;
}

// Strip ANY non-ASCII character from a string so jsPDF never encounters
// characters outside the Helvetica latin charset.
function safe(str) {
  return String(str || "").replace(/[^\x00-\x7F]/g, "");
}

function pageFooter(doc, pageNum, totalPages) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  // thin separator line
  doc.setDrawColor(220, 220, 220);
  doc.line(14, pageH - 12, pageW - 14, pageH - 12);

  doc.setFontSize(8);
  doc.setTextColor(160);
  doc.setFont("helvetica", "normal");

  // left — app name (NO emoji)
  doc.text("Generated by SpendWise", 14, pageH - 6);

  // centre — date
  doc.text(
    `Generated on ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`,
    pageW / 2, pageH - 6,
    { align: "center" }
  );

  // right — page number
  doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 14, pageH - 6, { align: "right" });

  doc.setTextColor(0);
}

// ── main export ──────────────────────────────────────────────────────────
export async function exportSpendWisePDF({
  username    = "User",
  totals,
  transactions = [],
  highlighted  = [],
  dailyRef,
  categoryRef,
  balanceRef,
  includeGraphs = true,
}) {
  const doc  = new jsPDF("p", "mm", "a4");
  const pageW = doc.internal.pageSize.getWidth();  // 210
  const pageH = doc.internal.pageSize.getHeight(); // 297

  // ── COVER / HEADER BAND ──────────────────────────────────────────────
  // dark header band
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageW, 36, "F");

  // SpendWise title
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("SpendWise", 14, 16);

  // subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("Personal Finance Report", 14, 24);

  // user + date on right
  doc.setFontSize(9);
  doc.setTextColor(203, 213, 225); // slate-300
  doc.text(`User: ${safe(username)}`, pageW - 14, 14, { align: "right" });
  doc.text(
    `Date: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`,
    pageW - 14, 21, { align: "right" }
  );
  doc.text(`Transactions: ${transactions.length}`, pageW - 14, 28, { align: "right" });

  // reset text colour
  doc.setTextColor(0);

  let y = 44;

  // ── SUMMARY CARDS (4: Credit / Debit / Net Cash / Balance) ──────────
  const cardW = (pageW - 28 - 9) / 4; // 4 cards with 3 gaps of 3mm
  const cardH = 20;
  const cardGap = 3;

  const cards = [
    { label: "Total Credit", value: fmtINR(totals.credit),   fill: [16, 185, 129]  },
    { label: "Total Debit",  value: fmtINR(totals.debit),    fill: [244, 63, 94]   },
    { label: "Net Cash",     value: fmtINR(totals.netCash ?? 0), fill: totals.netCash >= 0 ? [245, 158, 11] : [244, 63, 94] },
    { label: "Net Balance",  value: fmtINR(totals.balance),  fill: totals.balance >= 0 ? [59, 130, 246] : [244, 63, 94] },
  ];

  cards.forEach(({ label, value, fill }, i) => {
    const x = 14 + i * (cardW + cardGap);
    doc.setFillColor(...fill);
    doc.roundedRect(x, y, cardW, cardH, 3, 3, "F");
    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.text(label.toUpperCase(), x + 3, y + 6);
    doc.setFontSize(11);
    doc.text(value, x + 3, y + 15);
    doc.setTextColor(0);
    doc.setFont("helvetica", "normal");
  });

  y += cardH + 10;

  // ── FILTER SUMMARY LINE ──────────────────────────────────────────────
  // (simple metadata line so PDF reader knows what's filtered)
  doc.setFontSize(8);
  doc.setTextColor(100);
  const dateRange = (() => {
    if (!transactions.length) return "All transactions";
    const dates = transactions.map((t) => t.date).filter(Boolean).sort();
    return `${dates[0]} to ${dates[dates.length - 1]}`;
  })();
  doc.text(`Period: ${dateRange}  |  Records: ${transactions.length}`, 14, y);
  doc.setTextColor(0);
  y += 7;

  // ── GRAPHS ───────────────────────────────────────────────────────────
  if (includeGraphs) {
    const grab = async (ref) => {
      if (!ref?.current) return null;
      try {
        const canvas = await html2canvas(ref.current, { scale: 2, useCORS: true, logging: false });
        return canvas.toDataURL("image/png");
      } catch { return null; }
    };

    const [imgDaily, imgCat, imgBal] = await Promise.all([
      grab(dailyRef),
      grab(categoryRef),
      grab(balanceRef),
    ]);

    const gW  = (pageW - 28 - 8) / 3; // 3 charts equal width
    const gH  = 52;
    const gGap = 4;

    // chart labels
    const chartLabels = ["Daily Spend", "By Category", "Balance Trend"];
    const chartImgs   = [imgDaily, imgCat, imgBal];

    chartImgs.forEach((img, i) => {
      const x = 14 + i * (gW + gGap);
      // card bg
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(x, y, gW, gH + 8, 2, 2, "FD");
      // label
      doc.setFontSize(7);
      doc.setTextColor(100);
      doc.setFont("helvetica", "bold");
      doc.text(chartLabels[i].toUpperCase(), x + 3, y + 5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0);
      // image
      if (img) doc.addImage(img, "PNG", x + 2, y + 7, gW - 4, gH - 2);
      else {
        doc.setFontSize(8);
        doc.setTextColor(180);
        doc.text("No data", x + gW / 2, y + gH / 2 + 7, { align: "center" });
        doc.setTextColor(0);
      }
    });

    y += gH + 8 + 10;
  }

  // ── TRANSACTIONS HEADING ─────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Transaction Details", 14, y);
  y += 5;
  doc.setTextColor(0);

  // ── TRANSACTIONS TABLE ───────────────────────────────────────────────
  // Build table body — group by date, insert date header rows
  const tableBody = [];
  let lastDate    = null;

  for (const t of transactions) {
    // date group header row
    if (t.date !== lastDate) {
      lastDate = t.date;
      const label = (() => {
        try {
          return new Date(t.date + "T00:00:00").toLocaleDateString("en-IN", {
            weekday: "short", day: "2-digit", month: "short", year: "numeric",
          });
        } catch { return t.date; }
      })();
      tableBody.push([{ content: safe(label), colSpan: 5, styles: { fillColor: [241, 245, 249], fontStyle: "bold", fontSize: 8, textColor: [51, 65, 85], cellPadding: 2 } }]);
    }

    // cash direction label
    const typeLabel = (() => {
      if (t.type === "credit") return "Credit";
      if (t.type === "debit")  return "Debit";
      return t.cashDirection === "in" ? "Cash In" : "Cash Out";
    })();

    tableBody.push([
      safe(t.date),
      typeLabel,
      safe(t.category || "Other"),
      safe(t.description || ""),
      fmtINR(t.amount),
    ]);
  }

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14, bottom: 18 }, // leave room for footer
    head: [["Date", "Type", "Category", "Description", "Amount"]],
    body: tableBody,

    styles: {
      font:        "helvetica",
      fontSize:    8.5,
      cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
      overflow:    "linebreak",
    },

    headStyles: {
      fillColor:  [15, 23, 42],   // slate-900
      textColor:  255,
      fontStyle:  "bold",
      fontSize:   8,
    },

    alternateRowStyles: { fillColor: [248, 250, 252] },

    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 22 },
      2: { cellWidth: 32 },
      3: { cellWidth: "auto" },
      4: { cellWidth: 26, halign: "right" },
    },

    didParseCell(data) {
      if (data.section !== "body") return;
      // skip date-header rows (colSpan rows have no row.index in transactions)
      const t = transactions[data.row.index];
      if (!t) return;

      // highlighted rows → amber tint
      if (highlighted.includes(t.id)) {
        data.cell.styles.fillColor = [255, 248, 196];
        data.cell.styles.fontStyle = "bold";
      }

      // colour-code type column
      if (data.column.index === 1) {
        if (t.type === "credit" || t.cashDirection === "in") {
          data.cell.styles.textColor = [5, 150, 105];   // green
        } else {
          data.cell.styles.textColor = [220, 38, 38];   // red
        }
      }

      // amount column right-align colour
      if (data.column.index === 4) {
        data.cell.styles.textColor =
          t.type === "credit" || t.cashDirection === "in"
            ? [5, 150, 105]
            : [220, 38, 38];
      }
    },

    // add footer on each page
    didDrawPage(data) {
      const totalPages = doc.internal.getNumberOfPages();
      pageFooter(doc, data.pageNumber, totalPages);
    },
  });

  // fix footer on first page too (autoTable didDrawPage fires after the fact)
  const total = doc.internal.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    pageFooter(doc, p, total);
  }

  doc.save(`SpendWise_${safe(username)}_${new Date().toISOString().slice(0, 10)}.pdf`);
}